# Generated by Django 3.1.7 on 2021-02-24 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lcid', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='AccessibilityTestDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('INITIAL', 'INITIAL'), ('REMEDIATION', 'REMEDIATION')], default='INITIAL', max_length=100)),
                ('date', models.DateField()),
                ('score', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField()),
                ('accessibility_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='easi_api.accessibilityrequest')),
            ],
        ),
        migrations.AddField(
            model_name='accessibilityrequest',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system', to='easi_api.system'),
        ),
    ]
