# Generated by Django 3.1.7 on 2021-02-24 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easi_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessibilitytestdate',
            name='deleted_at',
        ),
    ]
